return {
	-- {
	-- 	"copilotlsp-nvim/copilot-lsp",
	-- 	init = function()
	-- 		vim.g.copilot_nes_debounce = 500
	-- 		vim.lsp.enable("copilot_ls")
	-- 		vim.keymap.set("n", "<C-y>", function()
	-- 			local _ = require("copilot-lsp.nes").walk_cursor_start_edit()
	-- 				or (
	-- 					require("copilot-lsp.nes").apply_pending_nes()
	-- 					and require("copilot-lsp.nes").walk_cursor_end_edit()
	-- 				)
	-- 		end)
	-- 		vim.keymap.set("n", "<esc>", function()
	-- 			if not require("copilot-lsp.nes").clear() then
	-- 				-- fallback to other functionality
	-- 			end
	-- 		end, { desc = "Clear Copilot suggestion or fallback" })
	-- 	end,
	-- },
}
