return {
	"rose-pine/neovim",
	lazy = false,
	name = "rose-pine",
	config = function()
		require("rose-pine").setup({
			styles = {
				transparency = true,
			},
			highlight_groups = {
				MatchParen = { fg = "love", bg = "love", blend = 25 },
				-- CursorLineNr = { fg = "gold", bold = true },
				StatusLineTerm = { fg = "subtle", bg = "none" },
				StatuslineSeparator = { fg = "none", bg = "none" },
				StatuslineTextMain = { fg = "text", bg = "none" },
				StatuslineTextBold = { link = "StatuslineTextMain", bg = "none", bold = true },
				StatuslineTextAccent = { fg = "muted", bg = "none" },
				StatuslineSpinner = { fg = "gold", bg = "none" },
				StatuslineModeCommand = { fg = "love", bg = "none", bold = true },
				StatuslineModeInsert = { fg = "foam", bg = "none", bold = true },
				StatuslineModeNormal = { fg = "pine", bg = "none", bold = true },
				StatuslineModeOther = { fg = "pine", bg = "none", bold = true },
				StatuslineModeReplace = { fg = "rose", bg = "none", bold = true },
				StatuslineModeVisual = { fg = "iris", bg = "none", bold = true },
				StatuslineLspOn = { fg = "gold", bg = "none" },
				StatuslineFormatterStatus = { fg = "foam", bg = "none" },
				StatuslineCopilot = { fg = "iris", bg = "none" },
				StatuslineRec = { fg = "love", bg = "none" },
				StatuslineScrollbar = { fg = "love", bg = "none" },
				StatuslineDiagnosticError = { fg = "love", bg = "none" },
				StatuslineDiagnosticWarn = { fg = "gold", bg = "none" },
				StatuslineDiagnosticInfo = { fg = "foam", bg = "none" },
				StatuslineDiagnosticHint = { fg = "iris", bg = "none" },
				StatuslineActiveHarpoon = { fg = "rose", bg = "none" },
				StatuslineNotSaved = { fg = "gold", bg = "none" },
				StatuslineReadOnly = { fg = "love", bg = "none" },
				StatuslineFilepath = { fg = "muted", bg = "none", italic = true },
				QuickFixFilename = { fg = "text" },
				CodeCompanionChatHeader = { fg = "rose" },
				CodeCompanionChatSeparator = { fg = "muted" },
				CodeCompanionChatTokens = { fg = "gold" },
				CodeCompanionChatTool = { fg = "pine" },
				CodeCompanionChatVariable = { fg = "none", bg = "iris" },
				CodeCompanionVirtualText = { fg = "iris" },
				DapUIStepOver = { fg = "foam" },
				DapUIStepInto = { fg = "foam" },
				DapUIStepBack = { fg = "foam" },
				DapUIStepOut = { fg = "foam" },
				DapUIStop = { fg = "love" },
				DapUIPlayPause = { fg = "pine" },
				DapUIRestart = { fg = "pine" },
				DapUIUnavailable = { fg = "muted" },
				IndentLineCurrent = { fg = "muted" },
				EasyDotnetTestRunnerSolution = { fg = "pine" },
				EasyDotnetTestRunnerProject = { fg = "rose" },
				EasyDotnetTestRunnerTest = { fg = "iris" },
				SnacksIndentScope = { fg = "overlay" },
				SnacksDashboardSpecial = { fg = "muted" },
				SnacksDashboardTitle = { fg = "text" },
				SnacksDashboardDesc = { fg = "muted" },
				SnacksDashboardDir = { fg = "muted", italic = true },
				SnacksDashboardFile = { fg = "text" },
				SnacksDashboardFooter = { fg = "text" },
				MiniIconsAzureBlend = { fg = "foam", bg = "foam", blend = 25 },
				MiniIconsBlueBlend = { fg = "pine", bg = "pine", blend = 25 },
				MiniIconsCyanBlend = { fg = "foam", bg = "foam", blend = 25 },
				MiniIconsGreenBlend = { fg = "leaf", bg = "leaf", blend = 25 },
				MiniIconsGreyBlend = { fg = "subtle", bg = "subtle", blend = 25 },
				MiniIconsOrangeBlend = { fg = "rose", bg = "rose", blend = 25 },
				MiniIconsPurpleBlend = { fg = "iris", bg = "iris", blend = 25 },
				MiniIconsRedBlend = { fg = "love", bg = "love", blend = 25 },
				MiniIconsYellowBlend = { fg = "gold", bg = "gold", blend = 25 },
				DartCurrentLabel = { fg = "gold", bg = "overlay", bold = true },
				DartCurrentModified = { fg = "text", bg = "overlay", bold = true },
				DartCurrentLabelModified = { fg = "gold", bg = "overlay", bold = true },
				DartVisibleLabel = { fg = "gold", bg = "surface", bold = true },
				DartVisibleLabelModified = { fg = "gold", bg = "text", bold = true },
				DartPickLabel = { fg = "gold", bg = "none", bold = true },
				WilderText = { fg = "text", bg = "none" },
				WilderMauve = { fg = "foam", bg = "none" },
				RenderMarkdownCode = { bg = "base" },
				RenderMarkdownCodeInline = { bg = "overlay" },
				RenderMarkdownInlineHighlight = { link = "RenderMarkdownCodeInline" },
			},
		})
		vim.cmd("colorscheme rose-pine")
	end,
}
